---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: site
  label: Pages
  create: all
  match: "**/*.md"
  exclude: workshop/*
  templates:
  - page
- type: heading
  label: Workshops
- type: directory
  path: site/workshop
  label: Posts
  create: documents
  match: "**/*"
  exclude: "{index.md,*.11tydata.json}"
  templates:
  - workshop-single
- type: document
  path: site/workshops.md
  label: Index
- type: heading
  label: Blog
- type: directory
  path: site/post
  label: Posts
  create: documents
  match: "**/*"
  exclude: "{index.md,*.11tydata.json}"
  templates:
  - post-single
upload_dir: coyote
public_path: https://res.cloudinary.com/marinaforhire
front_matter_path: ''
use_front_matter_path: true
file_template: ":year:/:month:/:filename:"
build:
  preview_env:
  - CLOUDINARY_NAME=marinaforhire
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run dev
